// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR8ibgVLngO1nqoPjxc0tve1r3fPzobh4',
    appId: '1:706451140993:web:ab7f40cb18e71a6dcff880',
    messagingSenderId: '706451140993',
    projectId: 'aquila-d3cd0',
    authDomain: 'aquila-d3cd0.firebaseapp.com',
    storageBucket: 'aquila-d3cd0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpSYkPNy2tUoNrD_ImqYdPcnn1GhWDepo',
    appId: '1:706451140993:android:2131e38233ae6e04cff880',
    messagingSenderId: '706451140993',
    projectId: 'aquila-d3cd0',
    storageBucket: 'aquila-d3cd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk6uZK6Vf1wAW7QmOUy0MS3esfKs9mgyw',
    appId: '1:706451140993:ios:9bdf157afee70c11cff880',
    messagingSenderId: '706451140993',
    projectId: 'aquila-d3cd0',
    storageBucket: 'aquila-d3cd0.firebasestorage.app',
    iosBundleId: 'com.example.aquila',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk6uZK6Vf1wAW7QmOUy0MS3esfKs9mgyw',
    appId: '1:706451140993:ios:9bdf157afee70c11cff880',
    messagingSenderId: '706451140993',
    projectId: 'aquila-d3cd0',
    storageBucket: 'aquila-d3cd0.firebasestorage.app',
    iosBundleId: 'com.example.aquila',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR8ibgVLngO1nqoPjxc0tve1r3fPzobh4',
    appId: '1:706451140993:web:3af87a26a27fffa3cff880',
    messagingSenderId: '706451140993',
    projectId: 'aquila-d3cd0',
    authDomain: 'aquila-d3cd0.firebaseapp.com',
    storageBucket: 'aquila-d3cd0.firebasestorage.app',
  );
}
